package com.hospital.hms.Enum;

public enum NotificationType {
    APPOINTMENT_REMINDER,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED,
    TEST_ASSIGNED,
    TEST_COMPLETED,
    PRESCRIPTION_CREATED,
    PRESCRIPTION_DISPENSED,
    INVOICE_CREATED,
    PAYMENT_RECEIVED,
    SYSTEM_ALERT,
    GENERAL
}
