spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hms_backend
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 25MB

jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  access-token-expiration: 900000        # 15 minutes (ms)
  refresh-token-expiration: 604800000    # 7 days     (ms)

logging:
  level:
    root: INFO
    com.hospital.hms: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html